#!/bin/bash

# manu:summary=First run icons
# manu:group=
# manu:name=first run icons

LOG="$HOME/.local/share/manu/first-run.log"
ICON_DIR="$HOME/.local/share/applications/icons"
MANU_APPS="$HOME/.local/share/manu/applications"

echo "$(date): Starting icons installation..." >>"$LOG"

mkdir -p "$ICON_DIR"
cp "$MANU_APPS/icons/"*.png "$ICON_DIR/"

echo "$(date): Icons installation completed." >>"$LOG"
