# General settings
general {
    lock_cmd = manu-system-lock
    before_sleep_cmd = MANU_LOCK_ONLY=true manu-system-lock       # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && manu-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3
}

# Start Screensaver after 5 minutes
listener {
    timeout = 300
    on-timeout = pidof hyprlock || manu-launch-screensaver
}


# Lock system after 10 minutes
listener {
    timeout = 600
    on-timeout = manu-system-lock
    on-resume = manu-system-wake
}


