-- Change the default Manu look'n'feel.
-- hl.config({
--   general = {
--     gaps_in = 0,
--     gaps_out = 0,
--     border_size = 0,
--     layout = "scrolling",
--   },
-- })
-- hl.config({
--   decoration = {
--     rounding = 8,
--     dim_inactive = true,
--     dim_strength = 0.15,
--   },
-- })
-- hl.config({
--   animations = {
--     enabled = false,
--   },
-- })
-- hl.config({
--   layout = {
--     single_window_aspect_ratio = { 1, 1 },
--   },
-- })
-- hl.config({
--   scrolling = {
--     column_width = 0.97,
--   },
-- })
